# -*- coding: utf-8 -*-
"""Metrick Generator.ipynb

Automatically generated by Colab.

1. Install the Vertex AI SDK: Open a terminal window and enter the command below. You can also [install it in a virtualenv](https://googleapis.dev/python/aiplatform/latest/index.html)
"""

!pip install --upgrade google-cloud-aiplatform

"""2. Use the following code in your application to request a model response"""

import base64
import vertexai
from vertexai.generative_models import GenerativeModel, Part, FinishReason
import vertexai.preview.generative_models as generative_models


def generate():
  vertexai.init(project="<your-project-id>", location="<your-google-server-location>")
  model = GenerativeModel(
    "gemini-1.5-flash-001",
  )
  responses = model.generate_content(
      ["""You are an expert in health, wellness, and finance. You are curating a multi-dimensional metric for an online biohacking game that reflects all the aspects of a persons self development incorporating all the areas of self improvement. You designing these metrics for the professionals so that they can use this with the clients.

Your Task
1. Generate a Health and Wellness Metric
Based on the following six inputs: [Profession], Focus Area], [Category], [Subcategory], [Level], and [Age Group], generate comprehensive health and wellness metrics for a biohacking game designed to improve users\' physical, mental, and emotional and financial well-being.

Before generating the metric, please briefly research and define the profession [Profession]. Focus on its primary goals, areas of practice, and any relevant aspects related to measuring progress of their clients/patients. Given the specific focus area of [Focus Area] within [Profession], generate a single metric relevant to measuring progress and well-being in clients/patients.

The metric should be quantifiable, easily interpretable, and adaptable to different lifestyles and goals within this [Profession]. Additionally, ensure the metric aligns with the specified difficulty level of [Difficulty Level] (1 being easy to track and 5 being very challenging to track) and is appropriate for the target age group of [Target Age Group]. Prioritise metrics that can be easily tracked and gamified within the context of an online game.

2. Output the metric in JSON format  with the following structure:

Metric Name: [Clear, concise name]
Description: [Offer a brief explanation of what the metric measures.]
Objectives: [Describe the goals or improvements this metric helps users achieve (in 1-2 sentences).]
Category: [Body, Mind, Work,  Growth, Wealth, Play, Habitat, Meaning, Bonds]
Subcategory: [Reference the Health Categories and Subcategories below for each subcategory e.g., Nutrition under Body]
Significance: [Why this metric is important for overall self-development]
Game Use: [How can this be integrated into the biohacking and self development game]
Unit of Measure: [Specify the appropriate unit (e.g., kg, minutes, rating scale).]
How to Measure: [Provide clear instructions on how users can collect data for this metric, including tools, frequency, and any special conditions.]
Normal Values: [Optional. If applicable, offer a range of typical values for this metric, ideally with age and sex considerations. If the metric is subjective, this can be omitted.]
References: [Provide a link or reference where the metric are sourced from if applicable]
Validated Measure: [Yes, No, N/A]
Target Age Group: [Target Age Group]
Target Level: [1Novice, 2 Savvy, 3 Elite, 4 Virtuoso, 5 Legend]
Result Type: [Quantitative, Qualitative, Temporal]
Result Type Subtype: [Quantitative (Continuous, Discrete), Qualitative (Categorical (Nominal, Ordinal), (Textual)), Temporal (Datetime, Duration, Frequency)
Additional Notes: [(Optional),  Include any extra information that might be helpful for users or developers, such as tips for improving the metric, potential limitations, or alternative measurement methods.]

3. Define Result Type:
Base Result Type: Specify whether the result is:
Quantitative (Numerical data)
Qualitative (Non-numerical data)
Temporal (Time-related data)

Subtype: If applicable, provide the appropriate subtype:
Quantitative: Continuous or Discrete
Qualitative: Categorical (Nominal or Ordinal) or Textual
Temporal: Datetime, Duration, or Frequency

Health Categories and Subcategories
Category: Body
Description: Encompasses all aspects of optimising your physical well-being, from fuelling and moving your body effectively to ensuring proper rest, recovery, and overall health.
Subcategories:
Nutrition, Fitness, Rest & Recovery, Preventative Care, Biohacking, , Health Monitoring

Category: Mind
Description: Cultivate mental and emotional well-being, enhance cognitive function, and develop psychological resilience.
Subcategories:
Emotional Well-being,Mental Health, Cognition, Mindfulness Practices, Brain Health.

Category: Work
Description: Optimise work performance, productivity, and career trajectory.
Subcategories:
Time Management, Productivity Systems,  Focus & Concentration, Career Development, Work, Environment, Habits.

Category: Growth
Description: Continuously evolve and expand through self-improvement, learning, and the pursuit of meaningful goals.
Subcategories:
Skills Acquisition, Goal Setting,  Self-Reflection, Creativity, Personal Development.

Category: Bonds
Description: Foster meaningful connections and build strong, supportive relationships.
Subcategories:
Romantic Relationships, Family Relationships, Friendships, Community, Communication.

Category: Wealth
Description: Achieve financial well-being and security.
Subcategories:
Budgeting, Investing, Financial Literacy, Income, Money Mindset,  Savings.

Category: Play
Description: Embrace joy, relaxation, and creative expression.
Subcategories:
Hobbies & Passions, Relaxation, Entertainment & Leisure, Playfulness, Adventure & Exploration.

Category: Meaning
Description: Explore your connection to something larger than yourself, clarify your values, discover your purpose.
Subcategories:
Mindfulness & Meditation, Spiritual Practices, Values, Purpose, Transcendence.

Category: Habitat
Description: Cultivate a harmonious relationship with your living environment.

Subcategories:
Sustainable Living, Nature Connection, Home Environment, Environmental Advocacy,
Green Spaces.

Age Groups:
Early Explorers (0-2 yrs)
Little Discoverers (3-5 yrs)
Young Learners (6-12 yrs)
Teen Innovators (13-19 yrs)
Career Navigators (20-29 yrs)
Prime Professionals (30-39 yrs)
Life Rebalancers (40-59 yrs)
Wisdom Keepers (60 yrs and Above)
Lifespan Hacks (All Age Groups)

Article: Profession: Registered Dietitian
Focus Area: Gut Health
Category: Body
Subcategory: Nutrition
Level: 3 Elite
Age Group: Life Rebalancers (40-59 years)

The title of above article can be: Metric Name: Gut Health Score,
Description: This metric assesses the overall health of your gut microbiome, taking into account dietary habits, symptoms, and lifestyle factors.,
Objectives: This metric helps users identify areas for improvement in their gut health and track progress towards a balanced and thriving microbiome.,
Category: Body,
Subcategory: Nutrition,
Significance: A healthy gut microbiome is essential for overall health and well-being. It influences digestion, immunity, mood, and even weight management.,
Game Use: Players can earn points for incorporating gut-healthy foods, tracking their symptoms, and engaging in activities that promote gut health.,
Unit of Measure: Score out of 100,
How to Measure: 1.  Dietary Analysis:  Use a food diary or app to record your food intake for 3-5 days, including portion sizes. 2.  Symptom Tracking:  Keep a journal or use a tracking app to record any digestive symptoms like bloating, gas, constipation, diarrhea, or changes in stool consistency. 3.  Lifestyle Assessment:  Consider factors like stress levels, sleep quality, physical activity, and alcohol consumption, which can influence gut health. 4.  Gut Health Questionnaire:  Complete a validated questionnaire specifically designed to assess gut health.  [Link to example questionnaire] 5.  Calculate Score: Based on the information gathered, the dietitian will assign points to each component of the assessment, totaling a Gut Health Score out of 100.  ,
Normal Values: Scores between 70-100 indicate good gut health. Scores between 50-69 suggest moderate gut health with potential for improvement. Scores below 50 may indicate poor gut health and require professional intervention.,
References: https://www.nature.com/articles/nrmicro2152,
Validated Measure: Yes,
Target Age Group: Life Rebalancers (40-59 years),
Target Level: 3 Elite
Result Type: Quantitative,
Result Type Subtype: Discrete,
Additional Notes: This metric can be customised based on individual needs and goals.  The dietitian should provide personalised guidance and support throughout the process. It\'s important to note that this metric is a starting point and should be used in conjunction with other assessments and consultations.


Article: Profession: Yoga Instructor
Focus Area: Spiritual Growth
Category: Growth
Subcategory: Mindfulness Practices
Level: 5 Legend
Age Group: Wisdom Keepers (60+ years)

The title of above article can be: Metric Name: Mindful Presence Score,
Description: This metric measures your ability to cultivate present moment awareness and cultivate a deeper sense of connection to your inner self and surroundings.,
Objectives: This metric helps users develop a greater capacity for mindful awareness, reduce stress and anxiety, and foster a deeper sense of peace and contentment.,
Category: Growth,
Subcategory: Mindfulness Practices,
Significance: Mindful presence is a core aspect of spiritual growth. It allows us to connect with the present moment, appreciate life\'s richness, and cultivate inner peace and wisdom.,
Game Use: Players can earn points for engaging in mindfulness practices, journaling about their experiences, and completing challenges designed to enhance their present moment awareness.,
Unit of Measure: Score out of 100,
How to Measure: 1. Self-Assessment:  Use a validated mindfulness scale or questionnaire to assess your current level of mindfulness.  2.  Mindful Activities:  Engage in regular mindfulness practices like meditation, deep breathing exercises, mindful walking, or body scans.  3.  Journaling:  Keep a journal to record your mindfulness experiences, including thoughts, feelings, and insights. 4.  Mindful Observation:  Pay attention to your senses and surroundings throughout the day. Notice the details of your environment, the sensations in your body, and the sounds around you. 5.  Integrate Mindfulness into Daily Activities:  Bring mindfulness to everyday tasks like eating, washing dishes, or interacting with others.  6. Reflect on Progress:  Review your journaling entries and self-assessments periodically to track your progress.  7. Score Calculation: The score will be calculated based on your self-assessments, journaling entries, and the frequency and duration of your mindfulness practices. The yoga instructor can provide guidance and feedback on your progress.,
Normal Values: N/A - This is a subjective measure.,
References: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4627291/,
Validated Measure: Yes,
Target Age Group: Wisdom Keepers (60+ years),
Target Level: 5 Legend
Result Type: Quantitative,
Result Type Subtype: Continuous,
Additional Notes: This metric can be challenging to track as it involves subjective self-assessment and requires dedication to mindful practices.  It is important to encourage patience and focus on the journey rather than solely focusing on the score.  Consider using a guided meditation app or a mindfulness teacher for support and guidance.


Article: Profession: Physical Therapist
Focus Area: Injury Prevention
Category: Body
Subcategory: Fitness
Level: 4 Virtuoso
Age Group: Career Navigators (20-29 years)

The title of above article can be: Metric Name: Movement Efficiency Score,
Description: This metric assesses your body\'s ability to move efficiently and effectively, reducing the risk of injury during daily activities and exercise.,
Objectives: This metric helps users identify areas for improvement in their movement patterns, optimise their training, and minimise the risk of injuries.,
Category: Body,
Subcategory: Fitness,
Significance: Efficient movement is crucial for injury prevention.  It reduces stress on joints and muscles, allowing for optimal performance and reducing the likelihood of overuse injuries.,
Game Use: Players can earn points for completing movement assessments, participating in corrective exercises, and demonstrating improved movement patterns during daily activities and workouts.,
Unit of Measure: Score out of 100,
How to Measure: 1. Movement Assessment:  Complete a comprehensive movement assessment with a qualified physical therapist, including assessments of: \\n - Range of Motion: Evaluate joint flexibility and mobility. \\n - Strength & Stability: Test muscle strength and core stability. \\n - Balance & Coordination: Assess dynamic balance and coordination. \\n - Posture Analysis:  Observe standing and sitting posture. \\n - Functional Movement Patterns: Assess basic movement patterns like squatting, lunging, and reaching. 2. Corrective Exercise Program:  Based on the assessment results,  participate in a personalised corrective exercise program designed to address movement limitations and improve overall efficiency. 3. Self-Monitoring:  Record your progress in a journal or app, noting any improvements in movement patterns, decreased pain or discomfort, and increased ease of movement during activities. 4. Score Calculation: The score will be calculated based on the results of the movement assessment, the consistency of your participation in the corrective exercise program, and your self-reported progress.,
Normal Values: N/A - This is a subjective measure.,
References: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4031590/,
Validated Measure: Yes,
Target Age Group: Career Navigators (20-29 years),
Target Level: 4 Virtuoso
Result Type: Quantitative,
Result Type Subtype: Continuous,
Additional Notes: This metric is challenging to track due to the need for a professional assessment and ongoing participation in a corrective exercise program. However, it can be gamified by allowing players to earn points for completing assessments, exercises, and achieving specific movement goals. Regular feedback from the physical therapist will be essential to guide progress and ensure effective injury prevention.


Article: Profession: Physical Therapist
Focus Area: Injury Prevention
Category: Body
Subcategory: Fitness
Level: 4 Virtuoso
Age Group: Career Navigators (20-29 years)

The title of above article can be: Metric Name: Functional Movement Quality Rating,
Description: This metric assesses the quality of your fundamental movement patterns, providing insights into potential injury risks and areas for improvement.,
Objectives: To help users understand their movement quality, identify imbalances or limitations, and make informed decisions about exercise and daily activities to prevent injuries.,
Category: Body,
Subcategory: Fitness,
Significance: Movement quality is a strong predictor of injury risk. Addressing movement deficiencies can significantly reduce the likelihood of injuries and enhance overall physical performance.,
Game Use: Players can earn points for completing movement assessments, engaging in corrective exercises, and demonstrating improvements in movement quality through video submissions or in-person evaluations.,
Unit of Measure: Qualitative rating scale (Excellent, Good, Fair, Poor),
How to Measure: 1. Movement Screen: Complete a standardised movement screen (e.g., Functional Movement Screen) with a qualified physical therapist. This screen will assess foundational movements like squatting, lunging, pushing, pulling, and rotating. 2. Qualitative Evaluation: The physical therapist will evaluate each movement pattern based on established criteria, such as range of motion, control, stability, and alignment. 3. Rating Assignment:  The physical therapist will assign an overall rating (Excellent, Good, Fair, Poor) based on the combined assessment of all movement patterns. This rating reflects your current movement quality.,
Normal Values: N/A - Movement quality is highly individual and varies based on factors like age, activity level, and injury history.,
References: Functional Movement Systems: Screening, Assessment, Corrective Strategies by Gray Cook,
Validated Measure: Yes,
Target Age Group: Career Navigators (20-29 years),
Target Level: 4 Virtuoso
Result Type: Qualitative,
Result Type Subtype: Categorical (Ordinal)
Additional Notes: This metric offers a comprehensive assessment of movement efficiency, providing valuable insights into potential injury risks and areas for improvement.   While it requires professional guidance and ongoing effort, it can be effectively gamified by awarding points for completing assessments, adhering to prescribed exercises, and demonstrating progress toward movement goals. Regular feedback from a physical therapist is essential to interpret results, tailor interventions, and ensure continued progress towards improved movement patterns and reduced injury risk.


Article: Profession: Health Coach
Focus Area: Lifestyle Consistency
Category: Body
Subcategory: Health Monitoring
Level: 2 Savvy
Age Group: Lifespan Hacks (All Age Groups)


The title of above article can be: Metric Name: Healthy Habit Streak,
Description: This metric tracks the longest consecutive period (in days) during which a user has successfully completed a predefined set of healthy habits.,
Objectives: To help users build and maintain healthy routines, promote consistent behaviour change, and visualise progress over time.,
Category: Body,
Subcategory: Health Monitoring,
Significance: Consistency is key to establishing long-term healthy habits and achieving desired health outcomes. Tracking streaks can be motivating and reinforce positive behaviour.,
Game Use: Players can earn points for each day they maintain their streak, with bonuses for reaching milestones (e.g., 7-day, 30-day, or 90-day streaks). Streak progress can be visually displayed in the game, fostering a sense of accomplishment.,
Unit of Measure: Days,
How to Measure: 1. Define Healthy Habits: Collaborate with the health coach to identify a set of 3-5 specific, measurable, and achievable healthy habits (e.g., eating 5 servings of vegetables daily, exercising for 30 minutes, getting 7-8 hours of sleep). 2. Daily Tracking: Use a habit tracker (app or journal) to record whether each habit was completed each day. 3. Calculate Streak: The streak is calculated as the longest continuous period of days where all selected habits were successfully completed. If a habit is missed on a given day, the streak resets to zero.,
Normal Values: N/A - Streaks will vary greatly depending on the individual and their chosen habits.,
References: Atomic Habits by James Clear,
Validated Measure: No - This is a self-reported measure, but can be reliable with consistent tracking.,
Target Age Group: Lifespan Hacks (All Age Groups),
Target Level: 2 Savvy
Result Type: Temporal,
Result Type Subtype: Duration
Additional Notes: This straightforward metric promotes consistent healthy behaviour by tracking the longest streak of completed habits. Its simplicity and focus on positive reinforcement make it suitable for all age groups. While self-reported, regular tracking enhances reliability. Users are encouraged to collaborate with health coaches to personalise habit selection and receive guidance throughout the process, maximising the metric\'s effectiveness for fostering long-term lifestyle changes.

Article: Profession: Physical Therapist
Focus Area: Injury Prevention
Category: Body
Subcategory: Fitness
Level: 4 Virtuoso
Age Group: Career Navigators (20-29 years)

The title of above article can be:
"""],
      generation_config=generation_config,
      safety_settings=safety_settings,
  )

  print(responses)


generation_config = {
    "max_output_tokens": 1024,
    "temperature": 0.2,
    "top_p": 0,
}

safety_settings = {
    generative_models.HarmCategory.HARM_CATEGORY_HATE_SPEECH: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
    generative_models.HarmCategory.HARM_CATEGORY_HARASSMENT: generative_models.HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
}

generate()